# This file was generated by GoReleaser. DO NOT EDIT.
cask "klimax" do
  version "0.1.52"

  on_macos do
    on_intel do
      sha256 "db55160ac38993c73a75153755ef536f065df19fa4ccd43dbbc4c92cc22c5851"
      url "https://github.com/bcollard/klimax/releases/download/v#{version}/klimax_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "619398c48560cdfebaf12ee6b3bcd46c51f42e2f847fbf69c54e2a3499e155c7"
      url "https://github.com/bcollard/klimax/releases/download/v#{version}/klimax_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "klimax"
  desc "Lima-based macOS VZ VM + multi-kind cluster manager"
  homepage "https://github.com/bcollard/klimax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klimax"

  # No zap stanza required

  caveats <<~EOS
    klimax bakes a specific kind CLI and default Kubernetes node image into the
    VM at creation time. Upgrading the klimax binary does NOT re-provision an
    existing VM, so after upgrading you should rebuild it:

      klimax destroy && klimax up

    Then recreate your clusters (klimax cluster create <name>). Skipping this can
    leave you on an older kind that cannot create the new default node version.
  EOS
end
