# This file was generated by GoReleaser. DO NOT EDIT.
cask "klimax" do
  version "0.1.64"

  on_macos do
    on_arm do
      sha256 "025b18fdb5f67ffee1253619e0d519525714d94d898157c4ffec6abb0ac62f46"
      url "https://github.com/bcollard/klimax/releases/download/v#{version}/klimax_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f8de7d718ebf7bc8dc92756449d72c95dba4d1427399ee7facd33db2525b8f4c"
      url "https://github.com/bcollard/klimax/releases/download/v#{version}/klimax_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "klimax"
  desc "Lima-based macOS VZ VM + multi-kind cluster manager"
  homepage "https://github.com/bcollard/klimax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klimax"

  # No zap stanza required

  caveats <<~EOS
    klimax bakes a specific kind CLI and default Kubernetes node image into the
    VM at creation time. Upgrading the klimax binary does NOT re-provision an
    existing VM, so after upgrading you should rebuild it:

      klimax destroy && klimax up

    Then recreate your clusters (klimax cluster create <name>). Skipping this can
    leave you on an older kind that cannot create the new default node version.
  EOS
end
