# This file was generated by GoReleaser. DO NOT EDIT.
cask "klimax" do
  version "0.1.63"

  on_macos do
    on_arm do
      sha256 "ddfdf48cc45c9812daa12c9d592e87f1113e1269895d2e6e56c3087b246518ba"
      url "https://github.com/bcollard/klimax/releases/download/v#{version}/klimax_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c659220a85c258151608ee1ab118df49d693c75b3543812c7287cb4288d2ff61"
      url "https://github.com/bcollard/klimax/releases/download/v#{version}/klimax_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "klimax"
  desc "Lima-based macOS VZ VM + multi-kind cluster manager"
  homepage "https://github.com/bcollard/klimax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klimax"

  # No zap stanza required

  caveats <<~EOS
    klimax bakes a specific kind CLI and default Kubernetes node image into the
    VM at creation time. Upgrading the klimax binary does NOT re-provision an
    existing VM, so after upgrading you should rebuild it:

      klimax destroy && klimax up

    Then recreate your clusters (klimax cluster create <name>). Skipping this can
    leave you on an older kind that cannot create the new default node version.
  EOS
end
