# This file was generated by GoReleaser. DO NOT EDIT.
cask "marina" do
  binary "marina", target: "klimax"

  version "0.3.3"

  on_macos do
    on_arm do
      sha256 "5e9052eef9e533924baf2d7d4dbc20c5149b58a269ce263c90560f1eea2aadb4"
      url "https://github.com/bcollard/marina/releases/download/v#{version}/marina_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "307b73ce6c9c1750e0db7f2ea132ac007434ee77cb2d3e171b8116adb3a0b98a"
      url "https://github.com/bcollard/marina/releases/download/v#{version}/marina_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "marina"
  desc "Lima-based macOS VZ VM + multi-kind cluster manager"
  homepage "https://marina.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marina"

  # No zap stanza required

  caveats <<~EOS
    Coming from klimax? Run `marina migrate` once: it moves ~/.klimax (config,
    registry cache) over and deletes the old VM. `klimax` stays available as an
    alias of `marina` for now.

    marina bakes a specific kind CLI and default Kubernetes node image into the
    VM at creation time. Upgrading the marina binary does NOT re-provision an
    existing VM, so after upgrading you should rebuild it:

      marina destroy && marina up

    Then recreate your clusters (marina cluster create <name>). Skipping this can
    leave you on an older kind that cannot create the new default node version.
  EOS
end
